In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

In [ ]:
df_learn = pd.read_csv('/content/drive/MyDrive/train.csv',nrows=3e6)
df_learn.isnull().sum()

Id                             0
minutes_past                   0
radardist_km                   0
Ref                      1598103
Ref_5x5_10th             1828896
Ref_5x5_50th             1595972
Ref_5x5_90th             1337585
RefComposite             1512873
RefComposite_5x5_10th    1720698
RefComposite_5x5_50th    1513445
RefComposite_5x5_90th    1273631
RhoHV                    1917697
RhoHV_5x5_10th           2088978
RhoHV_5x5_50th           1917832
RhoHV_5x5_90th           1711728
Zdr                      1917697
Zdr_5x5_10th             2088978
Zdr_5x5_50th             1917832
Zdr_5x5_90th             1711728
Kdp                      2077723
Kdp_5x5_10th             2239120
Kdp_5x5_50th             2076593
Kdp_5x5_90th             1892922
Expected                       0
dtype: int64

In [ ]:
df_learn = df_learn[~df_learn['Ref'].isnull()]
df_learn.isnull().sum()

Id                            0
minutes_past                  0
radardist_km                  0
Ref                           0
Ref_5x5_10th             233959
Ref_5x5_50th              40722
Ref_5x5_90th                 23
RefComposite                  0
RefComposite_5x5_10th    169719
RefComposite_5x5_50th     29299
RefComposite_5x5_90th        17
RhoHV                    506653
RhoHV_5x5_10th           612986
RhoHV_5x5_50th           501419
RhoHV_5x5_90th           392177
Zdr                      506653
Zdr_5x5_10th             612986
Zdr_5x5_50th             501419
Zdr_5x5_90th             392177
Kdp                      628867
Kdp_5x5_10th             740223
Kdp_5x5_50th             624964
Kdp_5x5_90th             507206
Expected                      0
dtype: int64

In [ ]:
df_learn.head(25)

    Id  minutes_past  radardist_km  ...  Kdp_5x5_50th  Kdp_5x5_90th  Expected
6    2             1           2.0  ...     -0.350006      1.059998  1.016000
7    2             6           2.0  ...           NaN      1.409988  1.016000
8    2            11           2.0  ...     -0.350006      1.759994  1.016000
9    2            16           2.0  ...      0.000000      1.059998  1.016000
10   2            21           2.0  ...     -0.350006      1.759994  1.016000
11   2            26           2.0  ...     -0.350006      0.709991  1.016000
12   2            31           2.0  ...     -0.710007      0.349991  1.016000
13   2            37           2.0  ...     -0.350006      1.059998  1.016000
14   2            42           2.0  ...      0.000000      0.349991  1.016000
15   2            47           2.0  ...     -0.350006      1.059998  1.016000
16   2            53           2.0  ...     -0.350006      2.119995  1.016000
17   2            58           2.0  ...     -0.350006      0.699997  1.016000
30   4             0           9.0  ...           NaN           NaN  4.064002
31   4             5           9.0  ...           NaN           NaN  4.064002
32   4             9           9.0  ...           NaN           NaN  4.064002
33   4            14           9.0  ...           NaN           NaN  4.064002
34   4            19           9.0  ...           NaN           NaN  4.064002
36   4            28           9.0  ...           NaN           NaN  4.064002
37   4            33           9.0  ...           NaN           NaN  4.064002
38   4            38           9.0  ...           NaN           NaN  4.064002
39   4            42           9.0  ...           NaN           NaN  4.064002
42   4            56           9.0  ...      0.000000      7.029999  4.064002
64   7             7          13.0  ...           NaN           NaN  0.508000
65   7            11          13.0  ...           NaN           NaN  0.508000
78   8             3           8.0  ...     -1.240006      4.459992  3.225002

[25 rows x 24 columns]

In [ ]:
import numpy as np

class RidgeRegScratch():
  # include solver parameter for flexible implementation of gradient descent
  # solution in future, alpha is used in place of lambda to mimic scikit-learn
  def __init__(self, alpha=1.0, solver='closed'):
      self.alpha = alpha
      self.solver = solver

  def fit(self, X, y):
      X_with_intercept = np.c_[np.ones((X.shape[0], 1)), X]
      self.X_intercept = X_with_intercept
      if self.solver == 'closed':
          # number of columns in matrix of X including intercept
          dimension = X_with_intercept.shape[1]
          # Identity matrix of dimension compatible with our X_intercept Matrix
          A = np.identity(dimension)
          # set first 1 on the diagonal to zero so as not to include a bias term for
          # the intercept
          A[0, 0] = 0
          # We create a bias term corresponding to alpha for each column of X not
          # including the intercept
          A_biased = self.alpha * A
          thetas = np.linalg.inv(X_with_intercept.T.dot(
              X_with_intercept) + A_biased).dot(X_with_intercept.T).dot(y)
      self.thetas = thetas
      return self

  def predict(self, X):
      thetas = self.thetas
      X_predictor = np.c_[np.ones((X.shape[0], 1)), X]
      self.predictions = X_predictor.dot(thetas)
      return self.predictions

In [ ]:
df_learn.fillna(0,inplace=True)
df_learn.shape

(1401897, 24)

In [ ]:
train_data=df_learn

In [ ]:
train_new_group = train_data.groupby('Id')
df = pd.DataFrame(train_new_group['Expected'].mean()) # mean, or any value
meaningful_ids = np.array(df[df['Expected'] < 73].index)
train_final = train_data[np.in1d(train_data.Id, meaningful_ids)]
train_final.shape
train_data=train_final
train_data.shape

(1372744, 24)

In [ ]:
train_data = train_data.groupby('Id')
expected = train_data['Expected'].mean().values
minutes_past=train_data['minutes_past'].max().values
ref=train_data['Ref'].mean().values
#ref1=train_data['Ref_5x5_10th'].mean().values
#ref5=train_data['Ref_5x5_50th'].mean().values
#ref9=train_data['Ref_5x5_90th'].mean().values
ref_c=train_data['RefComposite'].mean().values
#ref_c1=train_data['RefComposite_5x5_10th'].mean().values
#ref_c5=train_data['RefComposite_5x5_50th'].mean().values
#ref_c9=train_data['RefComposite_5x5_90th'].mean().values
rhohv=train_data['RhoHV'].mean().values
#rhohv1=train_data['RhoHV_5x5_10th'].mean().values
#rhohv5=train_data['RhoHV_5x5_50th'].mean().values
#rhohv9=train_data['RhoHV_5x5_90th'].mean().values
zdr=train_data['Zdr'].mean().values
#zdr1=train_data['Zdr_5x5_10th'].mean().values
#zdr5=train_data['Zdr_5x5_50th'].mean().values
#zdr9=train_data['Zdr_5x5_90th'].mean().values
kdp=train_data['Kdp'].mean().values
#kdp1=train_data['Kdp_5x5_10th'].mean().values
#kdp5=train_data['Kdp_5x5_10th'].mean().values
#kdp9=train_data['Kdp_5x5_10th'].mean().values
id=train_data['Id'].mean().values

In [ ]:
train_final=pd.DataFrame({'Id':id,
                          #'minutes_past':minutes_past,
                          'Ref':ref,
                          #'Ref_5x5_10th':ref1,
                          #'Ref_5x5_50th':ref5,
                          #'Ref_5x5_90th':ref9,
                          'RefComposite':ref_c,
                          #'RefComposite_5x5_10th':ref_c1,
                          #'RefComposite_5x5_50th':ref_c5,
                          #'RefComposite_5x5_90th':ref_c9,
                          'RhoHV':rhohv,
                          #'RhoHV_5x5_10th':rhohv1,
                          #'RhoHV_5x5_50th':rhohv5,
                          #'RhoHV_5x5_90th':rhohv9,
                          'Zdr':zdr,
                          #'Zdr_5x5_10th':zdr1,
                          #'Zdr_5x5_50th':zdr5,
                          #'Zdr_5x5_90th':zdr9,
                          'Kdp':kdp,
                          #'Kdp_5x5_10th':kdp1,
                          #'Kdp_5x5_50th':kdp5,
                          #'Kdp_5x5_90th':kdp9,
                          'Expected':expected})
train_final.head()

   Id        Ref  RefComposite     RhoHV       Zdr       Kdp  Expected
0   2  16.625000     22.666667  0.998611  0.380208 -0.264172  1.016001
1   4  26.600000     30.150000  0.098833 -0.112500  0.703000  4.064002
2   7  14.750000     16.000000  0.000000  0.000000  0.000000  0.508000
3   8  19.600000     24.200000  0.273167  0.412500 -0.105000  3.225002
4  10  33.958333     34.791667  0.902778  0.255208 -1.404172  0.010000

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
train_final.iloc[:,:-1]=sc.fit_transform(train_final.iloc[:,:-1])
train_final.shape
x=train_final.iloc[:,:-1]
y=train_final.iloc[:,-1]

In [ ]:
reg=RidgeRegScratch(alpha=0.001)
reg.fit(x,y)

In [ ]:
test_raw = pd.read_csv('/content/drive/MyDrive/test.csv',usecols=['Id','minutes_past','Ref','RefComposite','RhoHV','Zdr','Kdp'])
#test_raw = pd.read_csv('/content/drive/MyDrive/test.csv',nrows=2e6)
test_raw_ids_all = test_raw["Id"]
test_raw_ids = np.array(test_raw_ids_all.unique())
test_data = test_raw.groupby('Id')

minutes_past=test_data['minutes_past'].max().values
ref         =test_data['Ref'].mean().values
#ref1        =test_data['Ref_5x5_10th'].mean().values
#ref5        =test_data['Ref_5x5_50th'].mean().values
#ref9        =test_data['Ref_5x5_90th'].mean().values
ref_c =test_data['RefComposite'].mean().values
#ref_c1=test_data['RefComposite_5x5_10th'].mean().values
#ref_c5=test_data['RefComposite_5x5_50th'].mean().values
#ref_c9=test_data['RefComposite_5x5_90th'].mean().values
rhohv =test_data['RhoHV'].mean().values
#rhohv1=test_data['RhoHV_5x5_10th'].mean().values
#rhohv5=test_data['RhoHV_5x5_50th'].mean().values
#rhohv9=test_data['RhoHV_5x5_90th'].mean().values
zdr =test_data['Zdr'].mean().values
#zdr1=test_data['Zdr_5x5_10th'].mean().values
#zdr5=test_data['Zdr_5x5_50th'].mean().values
#zdr9=test_data['Zdr_5x5_90th'].mean().values
kdp =test_data['Kdp'].mean().values
#kdp1=test_data['Kdp_5x5_10th'].mean().values
#kdp5=test_data['Kdp_5x5_10th'].mean().values
#kdp9=test_data['Kdp_5x5_10th'].mean().values
id=test_data['Id'].mean().values
test_new=pd.DataFrame({'Id':id,
                       #'minutes_past':minutes_past,
                          'Ref':ref,
                          #'Ref_5x5_10th':ref1,
                          #'Ref_5x5_50th':ref5,
                          #'Ref_5x5_90th':ref9,
                          'RefComposite':ref_c,
                          #'RefComposite_5x5_10th':ref_c1,
                          #'RefComposite_5x5_50th':ref_c5,
                          #'RefComposite_5x5_90th':ref_c9,
                          'RhoHV':rhohv,
                          #'RhoHV_5x5_10th':rhohv1,
                          #'RhoHV_5x5_50th':rhohv5,
                          #'RhoHV_5x5_90th':rhohv9,
                          'Zdr':zdr,
                          #'Zdr_5x5_10th':zdr1,
                          #'Zdr_5x5_50th':zdr5,
                          #'Zdr_5x5_90th':zdr9,
                          'Kdp':kdp,
                          #'Kdp_5x5_10th':kdp1,
                          #'Kdp_5x5_50th':kdp5,
                          #'Kdp_5x5_90th':kdp9
                          })
test_new = test_new.fillna(0.0)
test_new.tail(25)
test_new.shape

(717625, 6)

In [ ]:
test_new=sc.transform(test_new)

In [ ]:
output=reg.predict(test_new)
output[:4]
for i in range(len(output)):
  if output[i]<0:
    output[i]=0

In [ ]:
my_submission = pd.DataFrame({'Id':np.arange(1,output.shape[0]+1),
                              'Expected': output})
my_submission.head()

   Id  Expected
0   1  0.079853
1   2  0.000000
2   3  3.138828
3   4  4.474417
4   5  0.000000

In [ ]:

actual=pd.read_csv('sample_solution.csv')
actual.head()

   Id  Expected
0   1  0.085765
1   2  0.000000
2   3  1.594004
3   4  6.913380
4   5  0.000000

In [ ]:
actual=actual["Expected"]
predicted=my_submission["Expected"]

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(actual,predicted, squared=False)

2.5689399126743875

In [ ]:
2.56